### PR TITLE
Issue69 bulk update links

### LINKED ISSUE #69: Support bulk link update action
We should have an endpoint like `/update_links` where users can send a set of copy / remove link revisions. Payload would look something like:

```
{ links: [ { dest: "metis://ipi/magma/record1-img_file1.jpg" source: "metis://ipi/magma/tmp-05050dd0f.jpg" }, { dest: "metis://ipi/magma/record1-img_file2.jpg", source: nil }, ... ] }
```

Each revision should be validated using the method that currently exists in the `file_copy` route, though minus the overwriting check (should allow overwriting), and perhaps also in bulk.

If any single update is invalid, the entire operation should be voided and an exception returned. None of the updates should occur in this scenario. **We do NOT want partial updates.**

### LINKED ISSUE #70: Copy file operation should let users overwrite existing files and folders?)
The current overwriting check does not follow standard copy UX. We should remove these checks (include folders? @graft )

```
raise Etna::Forbidden, 'Cannot copy over existing file' if Metis::File.exists?(new_file_name, new_bucket, new_folder)

    raise Etna::Forbidden, 'Cannot copy over existing folder' if  Metis::Folder.exists?(new_file_name, new_bucket, new_folder)

```

### PR DESCRIPTION
**Pull request by coleshaw**
Close #69 
Close #70 

@graft , what are your thoughts on this `bulk_update` route? It seems kind of busy / messy, since I basically have to loop through all the revisions twice. Can probably tighten it up, along with the existing routes, but wanted to get some feedback on the overall approach before refactoring.

### CODE REVIEW

**Comment by graft** [comment]
I think in general it's the right approach. However I'm a little concerned about the litany of tests which seems pretty non-systematic. What I suspect is that we need a low-level, safe operations interface that gets used by all controllers and would apply here. This seems a large project to accomplish at once.

I am also thinking about how the order of operations matters in determining what is valid, which seems very hard to satisfy.

**Comment by coleshaw** [comment]
Yeah, neither the code nor the tests are very DRY -- I basically copied the code and tests from both `remove` and `copy` to make sure that the `bulk_update` route covered at least the same basic use cases.

Do you want to me to at least try to refactor the `file_controller` routes to have more shared code / tests? Or save that for a future lower-level interface?

For order of validity checks, my approach was to reject as soon as possible ... but after the low hanging fruit, not sure how to best order the checks.

**Comment by coleshaw** [comment]
Just a couple thoughts on a low-level interface....

I feel like there are two types of checks at the controller level. One is the "syntax" check, like are all the parameters there, are they in the right format, etc. The other is the "authorization" check, like can this user view the bucket, edit the file, delete the file, etc. Is the authorization check the one that you're thinking can go into a low-level interface? Feels like something we could bake into the models (Metis::File.can_user_edit?) or have an internal service provider that does the checks for you (Metis::Authorization.can_user_edit_file?)...or a wrapper around each object that handles the checks (Metis::FileWithAuthz(File))? Okay, certainly some random thoughts.

**Comment by graft** [comment]
Let's cut scope here. We can leave out deletion since we agree it is not
strictly necessary, it can be added in later. That leaves a bulk copy
operation. Since everything is going into a single magma project bucket all
we care about is that the source files are legible - they exist and the
user can read them. This seems much easier to manage without a low-level
operations interface, which we can design later.

**Comment by coleshaw** [comment]
@graft , thoughts on this? I've left space for the remove functionality and removed related "remove" tests. Still not super clean, I think because of validating everything first...but probably won't be super clean until we get that low level interface...

File: lib/server/controllers/file_controller.rb [hunk 1]
```diff
@@ -104,4 +107,91 @@ def copy
...
+      # Here we check for removal or linkage
+      if revision[:dest]
+        new_bucket, new_folder, new_file_name = get_bucket_folder_file_from_path(revision[:dest])
+
+        # If the destination file exists, remove it before creating
+        #   the new link
+        if Metis::File.exists?(new_file_name, new_bucket, new_folder)
+          old_dest_file = get_file_obj_from_path(revision[:dest])
+          old_dest_file.remove!
+        end
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:182]: Why not just update the datablock instead of removing/recreating the file?

File: lib/server/controllers/file_controller.rb [hunk 2]
```diff
@@ -104,4 +107,91 @@ def copy
...
+    raise Etna::BadRequest, 'At least one revision required' unless revisions.length > 0
+
+    raise Etna::BadRequest, 'All revisions require "source" parameter' unless revisions.all? {|revision| revision.has_key? :source}
+    raise Etna::BadRequest, 'All revisions require "dest" parameter' unless revisions.all? {|revision| revision.has_key? :dest}
+
+    all_source_buckets = revisions.select {|rev| rev[:source]}.
+      map {|rev| extract_bucket_from_path(rev[:source])}.uniq
+    all_dest_buckets = revisions.select {|rev| rev[:dest]}.
+      map {|rev| extract_bucket_from_path(rev[:dest])}.uniq
+
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:131]: This might be nice in a revision object that collects all of these validations and bucket-extractions and so on.

File: lib/server/controllers/file_controller.rb [hunk 3]
```diff
@@ -104,4 +107,91 @@ def copy
...
+    user_authorized_bucket_names = Metis::Bucket.where(
+      project_name: @params[:project_name]
+    ).all.select{|b| b.allowed?(@user, @request.env['etna.hmac'])}.
+      map {|bucket| bucket.name}
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:135]: It might be easier to break down `Metis::Bucket#allowed?` here, and just extract the `id` (if any) from the valid hmac. Then you could retrieve all buckets `.where(owner: [ 'metis', id ], name: all_source_buckets + all_dest_buckets)`.

Comment (coleshaw) [reply lib/server/controllers/file_controller.rb:135]: Would that do the same ROLES check, if I skip `allowed?`? Seems like this would be actually more restrictive, right, only letting users copy to / from buckets where they are owners?

Comment (graft) [reply lib/server/controllers/file_controller.rb:135]: You're right, it wouldn't run those ROLES checks, and doing those checks in a db call is hard, so you'd have to use `allowed?` anyway, but adding in the owner and name requirements might let you pare down the number of buckets you are checking.

**Comment by coleshaw** [comment]
@graft , I've added in a `Revision` class and also cleaned up the controller code. I left the tests mostly as-is, was kind of torn between more low-level unit tests for the new shared methods, or  leaving the higher-level functional tests (which might be clearer in terms of expected behavior of the controllers?).

File: lib/revision.rb [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+          params[:source][:file_path]),
+        dest: path_from_parts(
+          params[:dest][:project_name],
+          params[:dest][:bucket_name],
+          params[:dest][:file_path])
+      })
+    end
+
+    def self.extract_bucket_name_from_path(path)
+      # Assumes Metis file paths are in the form
```
Comment (graft) [inline lib/revision.rb:43]: Not to go too deep down the rabbit hole of abstraction here, but since we are committing to this "metis path" notion, it probably deserves its own service object, e.g. `MetisPath.new(path).bucket_name`

Comment (graft) [reply lib/revision.rb:43]: A lot of the methods before could go away if we had `@source = MetisPath.new(source_path)`.

File: lib/revision.rb [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+        (?<file_path>(#{FILENAME_MATCH.source}).*)
+      \z
+    !x
+
+    attr_reader :source, :dest
+    def initialize(params)
+      raise Etna::BadRequest, 'All revisions require "source" parameter' unless params.has_key? :source
+      raise Etna::BadRequest, 'All revisions require "dest" parameter' unless params.has_key? :dest
+
+      raise Etna::BadRequest, 'Invalid source path' unless valid_file_path?(params[:source])
```
Comment (graft) [inline lib/revision.rb:21]: Since we can't be sure we're in a request here, we might not want to raise BadRequest to get out of here. Another option might be to just save the params and save these validations for a `valid?` method, which the controller can use to check if the request is valid and then raise BadRequest, etc. If not that we might raise out of here with some other error that we catch in the controller, but since this object has nothing better to do than provide validations it seems fine to leave them as methods rather than raising.

File: lib/server/controllers/file_controller.rb [hunk 6]
```diff
@@ -72,36 +74,115 @@ def rename
 
   def copy
     require_param(:new_file_path)
+
+    # Keep this here to verify the bucket is valid,
+    # since source bucket name is part of the path
     bucket = require_bucket
 
-    file = Metis::File.from_path(bucket, @params[:file_path])
+    raise Etna::Forbidden, "Cannot edit project #{@params[:project_name]}" unless @user.can_edit?(@params[:project_name])
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:82]: Hmm, should the route just be `can_edit? :project_name` instead of this? I think I initially thought: they only need to be able to read the file in the route path, not edit it - the edit permissions are for the write destination. If they are in the same project then the `can_edit?` permission should cover this. If not, the route should be `can_view?` and we should check if they can edit `new_project_name`. Since we don't support the latter at the moment it's probably easiest to just make the route `can_edit?`

File: lib/server/controllers/file_controller.rb [hunk 7]
```diff
@@ -72,36 +74,115 @@ def rename
...
     raise Etna::Forbidden, "Cannot edit project #{@params[:project_name]}" unless @user.can_edit?(@params[:project_name])
 
-    new_folder_path, new_file_name = Metis::File.path_parts(@params[:new_file_path])
+    revisions = []
 
-    new_bucket = require_bucket(@params[:new_bucket_name])
+    JSON.parse(@params[:revisions]).
+      each { |rev|
+        revisions.push(Metis::CopyRevision.new(rev.transform_keys(&:to_sym)))
+      }
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:126]: can do like: `JSON.parse(@params[:revisions], symbolize_names: true).map{|r| Metis::CopyRevision.new(rev)}`

File: lib/server/controllers/file_controller.rb (hunk 6 above)
Comment (coleshaw) [reply lib/server/controllers/file_controller.rb:82]: Oh yeah, I was wondering about this for the source file versus the destination file. Makes sense to just add it to the route definition, since we don't support changing projects at the moment.

File: lib/revision.rb (hunk 5 above)
Comment (coleshaw) [reply lib/revision.rb]: I didn't pass in the request -- thoughts on this `valid?` method? For bulk copy, I was trying to avoid fetching bucket for each revision, so passing in the list of authorized bucket names directly.

**Comment by coleshaw** [comment]
@graft refactored per your feedback. Thoughts? If it looks good I'll continue future work on different branches, to prevent this PR from getting too big.

File: lib/models/file.rb [hunk 8]
```diff
@@ -105,6 +105,35 @@ def self.exists?(file_name, bucket, parent_folder)
       Metis::File.where(file_name: file_name, bucket: bucket, folder_id: parent_folder ? parent_folder.id : nil).count > 0
     end
 
+    def self.copy(params)
+      # Assumes validations have been done, this just executes
+      #   the copy and returns the new copy.
+      dest_folder_path, dest_file_name = Metis::File.path_parts(params[:dest_file_path])
+
+      dest_bucket = Metis::Bucket.where(
+        project_name: params[:project_name],
```
Comment (graft) [inline lib/models/file.rb:114]: Can also be: `Metis::Bucket.find()`

File: lib/path.rb [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+        \z
+      !x
+
+      attr_reader :path
+      def initialize(path)
+        @path = path
+      end
+
+      def self.extract_bucket_name_from_path(path)
+        return FILEPATH_MATCH.match(path)[:bucket_name]
```
Comment (graft) [inline lib/path.rb:27]: Does this have value as a class method? Could these just be folded into `#bucket_name`, etc?

File: lib/server/controllers/file_controller.rb [hunk 10]
```diff
@@ -72,36 +74,116 @@ def rename
...
-    new_file = Metis::File.create(
-      project_name: @params[:project_name],
-      file_name: new_file_name,
-      folder_id: new_folder&.id,
-      bucket: new_bucket,
-      author: Metis::File.author(@user),
-      data_block: file.data_block
-    )
-    success_json(files: [ new_file.to_hash(@request) ])
+    raise Etna::Error.new("File #{revision.source.path} not found", 404) unless file&.has_data?
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:174]: This method definitely seems like it should be on the revision object. Generally I think it seems preferable to have all of the raising occurring in the controller, and have service objects handle the problem of determining error states. In this case, I think it's especially important not to raise until all of the errors have been collected - since the user may have submitted perhaps hundreds or thousands of revisions, they shouldn't have to discover and repair them one-by-one. The revision object can just collect the errors in an @errors method, which the controller can retrieve and compose an error message containing them. This probably allows the controller to only raise in one place, although it will almost certainly be forced to label everything as "bad request" rather than returning individual statuses.

File: lib/server/controllers/metis_controller.rb [hunk 11]
```diff
@@ -29,5 +29,23 @@ def require_folder(bucket, folder_path)
 
       return folder
     end
+
+    def get_file_obj_from_path(path)
```
Comment (graft) [inline lib/server/controllers/metis_controller.rb:33]: Could these move into Metis::Path itself?

File: lib/server/controllers/file_controller.rb [hunk 12]
```diff
@@ -72,36 +74,116 @@ def rename
...
 
-    new_folder = require_folder(new_bucket, new_folder_path)
+    hmac = @request.env['etna.hmac']
 
-    raise Etna::Forbidden, 'Folder is read-only' if new_folder&.read_only?
+    user_authorized_bucket_names = Metis::Bucket.where(
+      project_name: @params[:project_name],
+      owner: ['metis', hmac.id.to_s],
+      name: all_source_bucket_names + all_dest_bucket_names
+    ).all.select{|b| b.allowed?(@user, hmac)}.
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:140]: could be: `name: revision.map(&:bucket_names).flatten`

File: lib/server/controllers/file_controller.rb [hunk 13]
```diff
@@ -72,36 +74,116 @@ def rename
...
+      |rev| rev.valid?('source_bucket_access', user_authorized_bucket_names)}
+    raise Etna::Forbidden, 'User does not have access to all dest buckets' unless revisions.all? {
+      |rev| rev.valid?('dest_bucket_access', user_authorized_bucket_names)}
+
+    revisions.each do |revision|
+      validate_copy_revision(revision)
+    end
+
+    # If we've gotten here, every revision looks good and we can execute them!
+    new_files = []
```
Comment (graft) [inline lib/server/controllers/file_controller.rb:153]: You might consider moving this operation to the revision object also, in which case you could do: `success_json(files: revisions.map(&:revise!))`

**Comment by graft** [comment]
Very nice work. I think you can finish it up here, it's not that big, yet, and it seems nearly done(:crossed_fingers:). I think you should basically push more behavior out of the controller into the revision object (basically all of the validation stuff that is still in the controller); the controller I think will end up nice and lean, basically just laying out the high-level logic and raising errors, with all of the work happening in the revision object.

File: lib/server/controllers/file_controller.rb (hunk 10 above)
Comment (coleshaw) [reply lib/server/controllers/file_controller.rb:174]: K, that makes sense. I'll see if I can work that out.

File: lib/server/controllers/metis_controller.rb (hunk 11 above)
Comment (coleshaw) [reply lib/server/controllers/metis_controller.rb:33]: So one reason I left those here is that they also implicitly do some validation checks as part of the `require_bucket` call. Let me see how I can keep that behavior, especially for `copy` (I think we explicitly do the checks in `bulk_copy` already).

File: lib/server/controllers/file_controller.rb (hunk 13 above)
Comment (coleshaw) [reply lib/server/controllers/file_controller.rb:153]: Good idea!

File: lib/path.rb (hunk 9 above)
Comment (coleshaw) [reply lib/path.rb:27]: Only have it as a class method because I was using it in the `metis_controller` methods. Can remove it after I refactor those.

**Comment by coleshaw** [comment]
@graft , I think I've addressed all your comments about migrating validation and revision execution to `Revision` and keeping the Controller lean. Did I miss anything?

File: lib/path.rb [hunk 14]
```diff
@@ -0,0 +1,76 @@
...
+
+      FILENAME_MATCH=/[^<>:;,?"*\|\/\x00-\x1f]+/x
+
+      FILEPATH_MATCH=%r!
+        \A
+          metis:\/\/
+          (?<project_name>(#{FILENAME_MATCH.source}))
+          /
+          (?<bucket_name>(#{FILENAME_MATCH.source}))
+          /
```
Comment (graft) [inline lib/path.rb:16]: I think both project_name and bucket_name are only \w+; also I worry that FILENAME_MATCH here will diverge from the one in Metis::File. I guess you can't build the constant using Metis::File::FILENAME_MATCH because of load order issues? Alternatively you could build it on-demand in a memoized class method (like `def self.filepath_match; @filepath_match ||= etc.; end`)

Comment (coleshaw) [reply lib/path.rb]: That's a great point, especially if we decide to loosen up the restrictions on the filename. Load order does prevent just using `Metis::File::FILENAME_MATCH` directly, so I've changed it to a memoized class method.

**Comment by coleshaw** [comment]
@graft , does this help clarify the validations and what is happening?

**Comment by coleshaw** [comment]
@graft , sorry it's taken me so long to reach this point! Per our conversation, I've made the following changes:

* Added specs for `bulk_copy` to check for multiple source and destination buckets when using `bulk_copy` (with no errors and with errors)
* Error messages return as JSON instead of string, using `failure()` instead of Etna errors.
* Error messages are clearer, and for `bulk_copy` include the actual revisions associated with each error.

I will write up the analysis / thoughts we had for doing the validation stuff into #74.

This PR depends on mountetna/etna#50 -- could you take a look at that, too? If it looks good, I can merge and would be happy to publish if you set me up on RubyGems.

**Comment by coleshaw** [comment]
@graft, looks okay to merge?

**Comment by graft** [comment]
So much work! We should merge. One thing I would change is - in the specs many of the comments have diverged from their intent (especially in `file_spec.rb`) - could you amend these, then :shipit: ?
